on:
  push:
    branches:
      - master
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: -X GET "https://${{ secrets.DOMAIN_TEST }}"
